server:
  port: 5701
logging:
  file-location: logs

spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev

esctasy:
  qqchat:
    ws:
      socket-path: ${SOCKET_PATH:ws://localhost:5700}
      retry:
        enable: true
        max: 5
        interval: 3000
    third-chat:
      model: xx
      qingyun:
        api: xxx
      bard:
        token: xxxs
